apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: joseph0926/chatlink-auth:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: psql-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: psql-password
            - name: DATABASE_URL
              value: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-postgres-srv:5432/authdb"
            - name: ELASTIC_SEARCH_URL
              value: http://elasticsearch_container:9200
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: elasticsearch-username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: elasticsearch-password
            - name: API_GATEWAY_URL
              value: http://localhost:3001
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwt-key
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
