name: Server Dev CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies in the server directory
        run: |
          cd server
          cd auth-service
          npm install

      - name: Run ESLint and Prettier checks in packages
        run: |
          cd server
          cd auth-service
          npm run lint:check
          npm run prettier:check
